<a href="https://colab.research.google.com/github/amalendukithu06-cyber/DSA/blob/main/Case_Study_on_PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder

In [4]:
df = pd.read_csv("House_Pricing.csv")

df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [6]:
df.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [7]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 21613
Columns : 21

In [27]:
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

df = df.drop_duplicates()

print("Shape after removing duplicate rows:", df.shape)

Duplicate Rows: 0
Shape after removing duplicate rows: (16107, 37)

In [9]:
duplicate_columns = []

for i in range(df.shape[1]):
    col1 = df.iloc[:, i]

    for j in range(i + 1, df.shape[1]):
        col2 = df.iloc[:, j]

        if col1.equals(col2):
            duplicate_columns.append(df.columns[j])

print("Duplicate Columns:", duplicate_columns)

df = df.drop(columns=duplicate_columns)

print(df.shape)

Duplicate Columns: []
(21613, 21)

In [10]:
df.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [29]:
#Missing values Handling
num_cols = df.select_dtypes(include=['int64','float64']).columns

cat_cols = df.select_dtypes(include=['object']).columns

In [11]:
numerical_cols = df.select_dtypes(include=np.number).columns

categorical_cols = df.select_dtypes(include='object').columns

print(numerical_cols)

print(categorical_cols)

Index(['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')
Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [12]:
for col in numerical_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_861/518003605.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [13]:
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_861/1077209983.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [14]:
df.isnull().sum()

ID                                           0
Date House was Sold                          0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
No of Times Visited                          0
Condition of the House                       0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

In [31]:
num_features = num_cols.drop(target)

In [32]:
target = "Sale Price"

In [33]:
scale_columns = numerical_cols.drop(target)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[scale_columns] = scaler.fit_transform(df[scale_columns])

df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,221900.0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,Twice,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870228,-0.352545,-0.306112,-0.943328,-0.260715
1,0.637511,14 December 2017,538000.0,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,Twice,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879629,1.161615,-0.746380,-0.432658,-0.187868
2,0.365444,15 February 2016,180000.0,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,Twice,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933352,1.283585,-0.135686,1.070173,-0.172375
3,-0.727656,14 December 2017,604000.0,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,Twice,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085225,-0.283260,-1.271861,-0.914147,-0.284522
4,-0.912881,15 February 2016,510000.0,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,Twice,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073588,0.409587,1.199321,-0.272161,-0.192849

In [34]:
categorical_cols

Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [19]:
df = pd.get_dummies(df,
                    columns=categorical_cols,
                    drop_first=True)

In [36]:
cat_cols = df.select_dtypes(include='object').columns

print(cat_cols)

Index([], dtype='object')

In [35]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Example
# df["Condition"] = le.fit_transform(df["Condition"])

In [21]:
Q1 = df[scale_columns].quantile(0.25)

Q3 = df[scale_columns].quantile(0.75)

IQR = Q3 - Q1

In [22]:
df = df[~((df[scale_columns] < (Q1 - 1.5 * IQR)) |
          (df[scale_columns] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [23]:
print(df.shape)

(16107, 37)

In [24]:
X = df.drop(target, axis=1)

y = df[target]

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [38]:
print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)

print("Testing Labels :", y_test.shape)

Training Features : (12885, 36)
Testing Features : (3222, 36)
Training Labels : (12885,)
Testing Labels : (3222,)

In [39]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 16107 entries, 0 to 21612
Data columns (total 37 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         16107 non-null  float64
 1   Sale Price                                 16107 non-null  float64
 2   No of Bedrooms                             16107 non-null  float64
 3   No of Bathrooms                            16107 non-null  float64
 4   Flat Area (in Sqft)                        16107 non-null  float64
 5   Lot Area (in Sqft)                         16107 non-null  float64
 6   No of Floors                               16107 non-null  float64
 7   Overall Grade                              16107 non-null  float64
 8   Area of the House from Basement (in Sqft)  16107 non-null  float64
 9   Basement Area (in Sqft)                    16107 non-null  float64
 10  Age of House (in Years)                    16107 non-null  float64
 11  Renovated Year                             16107 non-null  float64
 12  Zipcode                                    16107 non-null  float64
 13  Latitude                                   16107 non-null  float64
 14  Longitude                                  16107 non-null  float64
 15  Living Area after Renovation (in Sqft)     16107 non-null  float64
 16  Lot Area after Renovation (in Sqft)        16107 non-null  float64
 17  Date House was Sold_14 December 2017       16107 non-null  bool
 18  Date House was Sold_14 July 2017           16107 non-null  bool
 19  Date House was Sold_14 June 2017           16107 non-null  bool
 20  Date House was Sold_14 May 2017            16107 non-null  bool
 21  Date House was Sold_14 November 2017       16107 non-null  bool
 22  Date House was Sold_14 October 2017        16107 non-null  bool
 23  Date House was Sold_14 September 2017      16107 non-null  bool
 24  Date House was Sold_15 April 2016          16107 non-null  bool
 25  Date House was Sold_15 February 2016       16107 non-null  bool
 26  Date House was Sold_15 January 2016        16107 non-null  bool
 27  Date House was Sold_15 March 2016          16107 non-null  bool
 28  Date House was Sold_15 May 2016            16107 non-null  bool
 29  Waterfront View_Yes                        16107 non-null  bool
 30  No of Times Visited_Once                   16107 non-null  bool
 31  No of Times Visited_Thrice                 16107 non-null  bool
 32  No of Times Visited_Twice                  16107 non-null  bool
 33  Condition of the House_Excellent           16107 non-null  bool
 34  Condition of the House_Fair                16107 non-null  bool
 35  Condition of the House_Good                16107 non-null  bool
 36  Condition of the House_Okay                16107 non-null  bool
dtypes: bool(20), float64(17)
memory usage: 2.5 MB
None

In [40]:
print(df.describe())

                 ID    Sale Price  No of Bedrooms  No of Bathrooms  \
count  16107.000000  1.610700e+04    16107.000000     16107.000000
mean       0.058082  4.605241e+05       -0.103079        -0.162913
std        0.993086  2.130999e+05        0.836713         0.845180
min       -1.591345  8.200000e+04       -1.473959        -1.772294
25%       -0.783540  3.060000e+05       -0.398737        -0.798333
50%       -0.181819  4.199500e+05       -0.398737        -0.149026
75%        1.016409  5.652500e+05        0.676485         0.500282
max        1.849366  2.400000e+06        1.751707         1.798896

       Flat Area (in Sqft)  Lot Area (in Sqft)  No of Floors  Overall Grade  \
count         16107.000000        16107.000000  16107.000000   16107.000000
mean             -0.251663           -0.194769     -0.044879      -0.185409
std               0.689357            0.081679      1.012956       0.742766
min              -1.655114           -0.352125     -0.915427      -1.468651
25%              -0.773032           -0.250058     -0.915427      -0.564013
50%              -0.326546           -0.195312     -0.915427      -0.564013
75%               0.196170           -0.147520      0.936506       0.340626
max               2.308811            0.097452      3.714405       1.245265

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
count                               16107.000000             16107.000000
mean                                   -0.228177                -0.095214
std                                     0.732007                 0.831003
min                                    -1.580259                -0.658681
25%                                    -0.770992                -0.658681
50%                                    -0.408634                -0.658681
75%                                     0.171139                 0.471097
max                                     2.357366                 2.504697

       Age of House (in Years)  Renovated Year       Zipcode      Latitude  \
count             16107.000000    1.610700e+04  16107.000000  16107.000000
mean                  0.003920   -2.101284e-01      0.068069      0.002802
std                   1.001816    8.471265e-14      1.010569      1.011875
min                  -1.497813   -2.101284e-01     -1.437997     -2.674306
25%                  -0.919045   -2.101284e-01     -0.839900     -0.670100
50%                  -0.067916   -2.101284e-01     -0.073588      0.081928
75%                   0.681079   -2.101284e-01      0.767486      0.880868
max                   2.417383   -2.101284e-01      2.262729      1.570107

          Longitude  Living Area after Renovation (in Sqft)  \
count  16107.000000                            16107.000000
mean      -0.142905                               -0.229012
std        0.877107                                0.762367
min       -2.052982                               -1.993851
25%       -0.874200                               -0.797423
50%       -0.398426                               -0.359705
75%        0.396897                                0.238509
max        2.789966                                2.412507

       Lot Area after Renovation (in Sqft)
count                         16107.000000
mean                             -0.214314
std                               0.110621
min                              -0.443805
25%                              -0.291847
50%                              -0.205777
75%                              -0.148660
max                               0.175125